# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/claims/v1/claims.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65vmos/claims/v1/claims.proto\x12\x0f\x65vmos.claims.v1\x1a\x14gogoproto/gogo.proto\"\x8d\x01\n\x05\x43laim\x12\'\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x17.evmos.claims.v1.Action\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x12H\n\x10\x63laimable_amount\x18\x03 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\"\x93\x01\n\x13\x43laimsRecordAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12P\n\x18initial_claimable_amount\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x12\x19\n\x11\x61\x63tions_completed\x18\x03 \x03(\x08\"{\n\x0c\x43laimsRecord\x12P\n\x18initial_claimable_amount\x18\x01 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x12\x19\n\x11\x61\x63tions_completed\x18\x02 \x03(\x08*\xd6\x01\n\x06\x41\x63tion\x12-\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x1a\x15\x8a\x9d \x11\x41\x63tionUnspecified\x12\x1f\n\x0b\x41\x43TION_VOTE\x10\x01\x1a\x0e\x8a\x9d \nActionVote\x12\'\n\x0f\x41\x43TION_DELEGATE\x10\x02\x1a\x12\x8a\x9d \x0e\x41\x63tionDelegate\x12\x1d\n\nACTION_EVM\x10\x03\x1a\r\x8a\x9d \tActionEVM\x12.\n\x13\x41\x43TION_IBC_TRANSFER\x10\x04\x1a\x15\x8a\x9d \x11\x41\x63tionIBCTransfer\x1a\x04\x88\xa3\x1e\x00\x42,Z*github.com/tharsis/evmos/v5/x/claims/typesb\x06proto3')

_ACTION = DESCRIPTOR.enum_types_by_name['Action']
Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
ACTION_UNSPECIFIED = 0
ACTION_VOTE = 1
ACTION_DELEGATE = 2
ACTION_EVM = 3
ACTION_IBC_TRANSFER = 4


_CLAIM = DESCRIPTOR.message_types_by_name['Claim']
_CLAIMSRECORDADDRESS = DESCRIPTOR.message_types_by_name['ClaimsRecordAddress']
_CLAIMSRECORD = DESCRIPTOR.message_types_by_name['ClaimsRecord']
Claim = _reflection.GeneratedProtocolMessageType('Claim', (_message.Message,), {
  'DESCRIPTOR' : _CLAIM,
  '__module__' : 'evmos.claims.v1.claims_pb2'
  # @@protoc_insertion_point(class_scope:evmos.claims.v1.Claim)
  })
_sym_db.RegisterMessage(Claim)

ClaimsRecordAddress = _reflection.GeneratedProtocolMessageType('ClaimsRecordAddress', (_message.Message,), {
  'DESCRIPTOR' : _CLAIMSRECORDADDRESS,
  '__module__' : 'evmos.claims.v1.claims_pb2'
  # @@protoc_insertion_point(class_scope:evmos.claims.v1.ClaimsRecordAddress)
  })
_sym_db.RegisterMessage(ClaimsRecordAddress)

ClaimsRecord = _reflection.GeneratedProtocolMessageType('ClaimsRecord', (_message.Message,), {
  'DESCRIPTOR' : _CLAIMSRECORD,
  '__module__' : 'evmos.claims.v1.claims_pb2'
  # @@protoc_insertion_point(class_scope:evmos.claims.v1.ClaimsRecord)
  })
_sym_db.RegisterMessage(ClaimsRecord)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*github.com/tharsis/evmos/v5/x/claims/types'
  _ACTION._options = None
  _ACTION._serialized_options = b'\210\243\036\000'
  _ACTION.values_by_name["ACTION_UNSPECIFIED"]._options = None
  _ACTION.values_by_name["ACTION_UNSPECIFIED"]._serialized_options = b'\212\235 \021ActionUnspecified'
  _ACTION.values_by_name["ACTION_VOTE"]._options = None
  _ACTION.values_by_name["ACTION_VOTE"]._serialized_options = b'\212\235 \nActionVote'
  _ACTION.values_by_name["ACTION_DELEGATE"]._options = None
  _ACTION.values_by_name["ACTION_DELEGATE"]._serialized_options = b'\212\235 \016ActionDelegate'
  _ACTION.values_by_name["ACTION_EVM"]._options = None
  _ACTION.values_by_name["ACTION_EVM"]._serialized_options = b'\212\235 \tActionEVM'
  _ACTION.values_by_name["ACTION_IBC_TRANSFER"]._options = None
  _ACTION.values_by_name["ACTION_IBC_TRANSFER"]._serialized_options = b'\212\235 \021ActionIBCTransfer'
  _CLAIM.fields_by_name['claimable_amount']._options = None
  _CLAIM.fields_by_name['claimable_amount']._serialized_options = b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000'
  _CLAIMSRECORDADDRESS.fields_by_name['initial_claimable_amount']._options = None
  _CLAIMSRECORDADDRESS.fields_by_name['initial_claimable_amount']._serialized_options = b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000'
  _CLAIMSRECORD.fields_by_name['initial_claimable_amount']._options = None
  _CLAIMSRECORD.fields_by_name['initial_claimable_amount']._serialized_options = b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000'
  _ACTION._serialized_start=491
  _ACTION._serialized_end=705
  _CLAIM._serialized_start=72
  _CLAIM._serialized_end=213
  _CLAIMSRECORDADDRESS._serialized_start=216
  _CLAIMSRECORDADDRESS._serialized_end=363
  _CLAIMSRECORD._serialized_start=365
  _CLAIMSRECORD._serialized_end=488
# @@protoc_insertion_point(module_scope)
